names=[]
inf=input("Input name 1,")
names.insert(0,inf)
ing=input("Input name 2,")
names.insert(0,ing)
inh=input("Input name 3,")
names.insert(0,inh)
inj=input("Input name 4,")
names.insert(0,inj)
ink=input("Input name 5,")
names.insert(0,ink)
inl=input("Input name 6,")
names.insert(0,inl)
inq=input("Input name 7,")
names.insert(0,inq)
inw=input("Input name 8,")
names.insert(0,inw)
ine=input("Input name 9,")
names.insert(0,ine)
inp=input("Input name 10,")
names.insert(0,inp)
names.sort()
print(names[0:5], "are is group A")
print(names[5:10], "are is group B")
